fragment DegreeFields on degree {
  slug
  title
  short_title
  course_code
  summary
  learning_outcomes
}

fragment DegreeCompactFields on degree {
  slug
  title
  short_title
  course_code
  description
}
