query Campus {
  campus_locations {
    ...CampusCoreFields
  }
}

query CampusDetails($slug: String!) {
  campus_locations(filter: { slug: { _eq: $slug } }) {
    ...CampusCoreFields
    description
    addtional_info_section
  }

  campus_locations_files(
    filter: { campus_locations_id: { slug: { _eq: $slug } } }
  ) {
    directus_files_id {
      ...FileFields
    }
  }
}
