query CourseDetail($slug: String!, $parent: String!) {
  courses(filter: { slug: { _eq: $slug }, degree: { slug: { _eq: $parent } } }) {
    ...CourseDetailFields
  }
  otherCourses: courses(filter: { slug: { _neq: $slug } }) {
    ...CourseSummaryFields
  }
}
