query CustomPage($slug: String!, $parent: String!) {
  pages(
    filter: {
      _and: [{ slug: { _eq: $slug } }, { parent_directory: { _eq: $parent } }]
    }
  ) {
    view_title_in_banner
    slug
    title
    description
    sections {
      ...SectionFields
    }
  }
}
