query DegreeDetail($slug: String!) {
  degree(filter: { slug: { _eq: $slug } }) {
    ...DegreeCompactFields
    summary
    learning_outcomes
    additional_content
    course {
      ...CourseDetailFields
    }
  }
}
