query Header {
  degree {
    slug
    title
    course {
      ...CourseCoreFields
    }
  }
  courses {
    ...CourseCoreFields
  }
  campus_locations {
    title
    slug
    icon
  }
  announcements {
    announcement_text
  }
  login_links {
    links
  }
}
