export const CHIEAgentData = [
  {
    title: "Aecc Global - AECC Global",
    phone: "+977 9283019900",
    website: "www.aeccglobal.com",
    address: "Sydney",
    country: "Australia",
    email: "info@aeccglobal.com",
    agentName: "Aradhana Sethi",
    imageUrl: "/assets/aecc.webp",
  },
  {
    title: "PME Global",
    phone: "+977 9283019900",
    website: null,
    address: "Sydney",
    country: "Nepal",
    email: "admissions@pmeglobal.com.au",
    agentName: "Kanika",
    imageUrl: "/assets/pme.jpg",
  },
  {
    title: "Ultimate Consultancy & Advisory Network",
    phone: "+61 11002033",
    website: null,
    address: "Sydney",
    country: "Nepal",
    email: "btamang@ucanlogin.com",
    agentName: "Nirajan Panta",
    imageUrl: "/assets/ucan.webp",
  },
  {
    title: "Oxford Education & Visa Services",
    phone: "+61 11002033",
    website: null,
    address: "Sydney",
    country: "India",
    email: "oxfordacademia.admission@gmail.com",
    agentName: "Prajwol Kafle",
    imageUrl: "/assets/oxford.png",
  },
  {
    title: "Shri Krishna Education & Immigration Consultants",
    phone: "+61 11002033",
    website: "shrikrishnaconsultants.com",
    address: "Sydney",
    country: "Australia",
    email: "info@shrikrishnaconsultants.com",
    agentName: "Manish Paul Garg",
    imageUrl: "/assets/shre.jpg",
  },
  {
    title: "Learn Quest Consultancy Services",
    phone: "+977 9283019900",
    website: null,
    address: "Sydney",
    country: "Nepal",
    email: "learnquestcons@gmail.com",
    agentName: "Navjot Singh",
    imageUrl: "/assets/learn.png",
  },
  {
    title: "The Sunshine Immigration Consultancy",
    phone: "+977 9283019900",
    website: "www.sunshineimmi.com",
    address: "Sydney",
    country: "India",
    email: "australia2@sunshineimmi.com",
    agentName: "Chirag Verma",
    imageUrl: "/assets/sunshine.png",
  },
];
