export const UpcomingKeyData = [
  {
    date: "2024-01-20",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "Continuing Student Enrolment Commences",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-01-23",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "Continuing Student Enrolment Commences",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-03-22",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "Orientation",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-03-25",
    endDate: "2024-05-05",
    startTime: null,
    endTime: null,
    eventName: "Classes (Week 1 to 6)",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-04-12",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "Census Date",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-05-06",
    endDate: "2024-05-12",
    startTime: null,
    endTime: null,
    eventName: "Mid Semester Break",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-05-13",
    endDate: "2024-06-23",
    startTime: null,
    endTime: null,
    eventName: "Classes (Week 7 to 12)",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-06-24",
    endDate: "2024-06-30",
    startTime: null,
    endTime: null,
    eventName: "Study Break",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-07-01",
    endDate: "2024-07-14",
    startTime: null,
    endTime: null,
    eventName: "Examination Weeks",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-07-15",
    endDate: "2024-07-28",
    startTime: null,
    endTime: null,
    eventName: "Mid Year Break",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-07-26",
    eventName: "Orientation (for commencing students only)",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-07-29",
    endDate: "2024-09-08",
    startTime: null,
    endTime: null,
    eventName: "Classes (Week 1 to 6)",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-08-16",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "Census Date",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-09-09",
    endDate: "2024-09-15",
    startTime: null,
    endTime: null,
    eventName: "Mid Semester Break",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-09-16",
    endDate: "2024-10-27",
    startTime: null,
    endTime: null,
    eventName: "Classes (Week 7 to 12)",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-10-28",
    endDate: "2024-11-03",
    startTime: null,
    endTime: null,
    eventName: "Study Break",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-11-04",
    endDate: "2024-11-17",
    startTime: null,
    endTime: null,
    eventName: "Examination Weeks",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-03-29",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "Good Friday",
    description: "",
    audience: ["Staff", "Student", "Undergraduate", "Postgraduate"],
    category: ["Days of Interest"],
  },
  {
    date: "2024-04-01",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "Easter Monday",
    description: "",
    audience: ["Staff", "Student", "Undergraduate", "Postgraduate"],
    category: ["Days of Interest"],
  },
  {
    date: "2024-04-25",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "Anzac Day",
    description: "",
    audience: ["Staff", "Student", "Undergraduate", "Postgraduate"],
    category: ["Days of Interest"],
  },
  {
    date: "2024-06-10",
    endDate: null,
    endTime: null,
    startTime: null,
    eventName: "King's Birthday",
    description: "",
    audience: ["Staff", "Student", "Undergraduate", "Postgraduate"],
    category: ["Days of Interest"],
  },
  {
    date: "2024-10-07",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "Labour Day",
    description: "",
    audience: ["Staff", "Student", "Undergraduate", "Postgraduate"],
    category: ["Days of Interest"],
  },
  {
    date: "2024-11-08",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "Orientation",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-11-11",
    endDate: "2024-12-22",
    startTime: null,
    endTime: null,
    eventName: "Classes (Week 1 to 6)",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-11-29",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "Census Date",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },

  {
    date: "2024-12-23",
    endDate: "2025-01-05",
    startTime: null,
    endTime: null,
    eventName: "Mid Semester Break",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-12-25",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "Christmas Day",
    description: "",
    audience: ["Staff", "Student", "Undergraduate", "Postgraduate"],
    category: ["Days of Interest"],
  },
  {
    date: "2024-12-26",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "Boxing Day",
    description: "",
    audience: ["Staff", "Student", "Undergraduate", "Postgraduate"],
    category: ["Days of Interest"],
  },
  {
    date: "2024-12-26",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "Boxing Day",
    description: "",
    audience: ["Staff", "Student", "Undergraduate", "Postgraduate"],
    category: ["Days of Interest"],
  },
  {
    date: "2025-01-06",
    endDate: "2025-02-16",
    startTime: null,
    endTime: null,
    eventName: "Classes (Week 7 to 12)",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2025-02-17",
    endDate: "2025-02-23",
    startTime: null,
    endTime: null,
    eventName: "Study Break",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2025-02-24",
    endDate: "2025-03-07",
    startTime: null,
    endTime: null,
    eventName: "Examination Weeks",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Semester dates"],
  },
  {
    date: "2024-12-25",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "Christmas Day",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Public holidays"],
  },
  {
    date: "2024-12-26",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "Boxing Day",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Public holidays"],
  },
  {
    date: "2025-01-01",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "New Year's Day",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Public holidays"],
  },
  {
    date: "2025-01-27",
    endDate: null,
    startTime: null,
    endTime: null,
    eventName: "Australia Day",
    description: "",
    audience: ["Student", "Undergraduate", "Postgraduate"],
    category: ["Public holidays"],
  },
];
