export const usefulLinksData = [
  {
    icon: "/assets/course-a.png",
    title: "Accounting Major",
    slug: "accounting-major",
    link:'',
    subTitle: "Bachelor of Business",
    Catagories: [],
  },
  {
    icon: "/assets/course-b.png",
    title: "Major in Information Systems",
    slug: "major-in-information-systems",
    link:'',
    subTitle: "Bachelor of Business",
    Catagories: [],
  },
  {
    icon: "/assets/course-c.png",
    title: "Major in Management",
    slug: "major-in-management",
    link:'',
    subTitle: "Bachelor of Business",
    Catagories: [],
  },
  {
    icon: "/assets/course-d.png",
    title: "Major in Hospitality",
    slug: "major-in-hospitality",
    link:'',
    subTitle: "Bachelor of Business",
    Catagories: [],
  },
  {
    icon: "/assets/course-a.png",
    title: "Accounting Major",
    slug: "accounting-major",
    link:'',
    subTitle: "Bachelor of Business",
    Catagories: [],
  },
  {
    icon: "/assets/course-b.png",
    title: "Major in Information Systems",
    slug: "major-in-information-systems",
    link:'',
    subTitle: "Bachelor of Business",
    Catagories: [],
  },
  {
    icon: "/assets/course-c.png",
    title: "Major in Management",
    slug: "major-in-management",
    link:'',
    subTitle: "Bachelor of Business",
    Catagories: [],
  },
  {
    icon: "/assets/course-d.png",
    title: "Major in Hospitality",
    slug: "major-in-hospitality",
    link:'',
    subTitle: "Bachelor of Business",
    Catagories: [],
  },
];
